"""
geoCampaigns — shared, persistent store of GEO campaigns for the GEO Analytics Dashboard.

Purpose: REPLICATE Workduo campaigns without depending on Workduo at runtime. It imports
campaign DEFINITIONS from Workduo once (brand, domain, competitors, tracked prompts, region),
stores them in DynamoDB, and serves them to every user of index.html. Metrics are NOT taken
from Workduo — they are regenerated by our own DataForSEO engine and saved back here, so the
dashboard's numbers are entirely our own data.

Actions (POST JSON {action, ...}):
  workduo_projects            -> list available Workduo projects (id, name, entity) to choose from
  import {projectIds, dryRun} -> pull definitions for those projects from Workduo, store in DynamoDB
  list                        -> all stored campaigns (definition + whether metrics exist)
  get {id}                    -> one campaign incl. saved metrics
  save_metrics {id, model}    -> persist a regenerated metrics snapshot (shared across users)
  delete {id}                 -> remove a campaign

Pure stdlib + boto3 (bundled in the Lambda runtime). Env: WORKDUO_PUBLIC_KEY, WORKDUO_SECRET_KEY,
CAMPAIGNS_TABLE (default 'geoCampaigns').
"""

import base64
import json
import os
import re
import time
import urllib.error
import urllib.request
from datetime import datetime, timedelta, timezone

import boto3
from boto3.dynamodb.conditions import Key

WD_PUB = os.environ.get("WORKDUO_PUBLIC_KEY", "")
WD_SEC = os.environ.get("WORKDUO_SECRET_KEY", "")
TABLE_NAME = os.environ.get("CAMPAIGNS_TABLE", "geoCampaigns")
WD_CORE = "https://api.workduo.ai/core/v1"
WD_DATA = "https://api.workduo.ai/data/v1"
TIMEOUT = int(os.environ.get("HTTP_TIMEOUT", "30"))

CORS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "content-type",
    "Access-Control-Allow-Methods": "POST,OPTIONS",
}

DAILY_TABLE = os.environ.get("DAILY_TABLE", "geoCampaignDaily")
_ddb = boto3.resource("dynamodb")
_table = _ddb.Table(TABLE_NAME)
_daily_tbl = _ddb.Table(DAILY_TABLE)


def _resp(status, body):
    return {"statusCode": status, "headers": {"Content-Type": "application/json", **CORS},
            "body": json.dumps(body, default=str)}


def _wd_get(url, params=None):
    if params:
        from urllib.parse import urlencode
        url = url + ("&" if "?" in url else "?") + urlencode(params)
    req = urllib.request.Request(url, method="GET")
    req.add_header("Authorization", "Basic " + base64.b64encode(f"{WD_PUB}:{WD_SEC}".encode()).decode())
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            return r.status, json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read().decode())
        except Exception:
            return e.code, {"error": f"HTTP {e.code}"}
    except Exception as e:
        return 0, {"error": str(e)}


def domain_of(u):
    if not u:
        return ""
    u = re.sub(r"^https?://", "", str(u)).split("/")[0]
    return re.sub(r"^www\.", "", u).lower()


def _rows(payload):
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict):
        return payload.get("data") or payload.get("results") or payload.get("items") or []
    return []


def fetch_workduo_projects():
    """Returns list of {id, name, entity:{...}} across all pages."""
    out, page = [], 1
    while True:
        status, body = _wd_get(f"{WD_CORE}/projects", {"page": page, "pageSize": 100})
        if status != 200:
            break
        batch = _rows(body)
        if not batch:
            break
        out.extend(batch)
        if (isinstance(body, dict) and body.get("hasNextPage") is False) or len(batch) < 100:
            break
        page += 1
        if page > 20:
            break
    return out


def _first(d, *keys, default=None):
    for k in keys:
        if isinstance(d, dict) and d.get(k) not in (None, ""):
            return d[k]
    return default


def extract_definition(project):
    """Pull a campaign definition from a Workduo project, probing several endpoint
    shapes for competitors and prompts. Returns (definition, diagnostics)."""
    pid = str(project.get("id"))
    entity = project.get("entity") or {}
    eid = entity.get("id")
    name = _first(project, "name", default=pid)
    target = _first(entity, "url", "domain", "website", default="")
    loc = project.get("location") or {}
    region = _first(loc, "region", "country", default=_first(project, "defaultRegion", "region", default="Singapore"))
    alt = entity.get("alternativeNames") or entity.get("aliases") or []
    diag = {}

    # --- Competitors: try inline first, then candidate endpoints ---
    competitors = []
    inline_ents = project.get("entities") or project.get("competitors") or []
    for e in inline_ents:
        if not isinstance(e, dict):
            continue
        tag = (e.get("tag") or e.get("type") or "").lower()
        if e.get("id") == eid or tag in ("primary", "self", "brand"):
            continue
        competitors.append(e.get("name") or e.get("entityName") or "")
    if not competitors:
        for url in (f"{WD_CORE}/projects/{pid}/entities", f"{WD_CORE}/entities",
                    f"{WD_DATA}/entities", f"{WD_CORE}/projects/{pid}/competitors"):
            params = {"projectId": pid} if "projects/" not in url else None
            st, body = _wd_get(url, params)
            diag[url] = st
            if st == 200:
                for e in _rows(body):
                    if not isinstance(e, dict):
                        continue
                    if e.get("id") == eid:
                        continue
                    tag = (e.get("tag") or e.get("type") or "").lower()
                    if tag in ("primary", "self", "brand"):
                        continue
                    nm = e.get("name") or e.get("entityName") or ""
                    if nm:
                        competitors.append(nm)
                if competitors:
                    break

    # --- Prompts / tracked queries (Workduo: /core/v1/queries?projectId, text in `query`) ---
    prompts, queries = [], []
    for url in (f"{WD_CORE}/queries", f"{WD_CORE}/projects/{pid}/queries", f"{WD_DATA}/queries"):
        params = {"projectId": pid, "pageSize": 200} if "projects/" not in url else {"pageSize": 200}
        st, body = _wd_get(url, params)
        diag[url] = st
        if st == 200:
            for p in _rows(body):
                if isinstance(p, str):
                    prompts.append(p)
                    queries.append({"text": p, "topic": "General", "region": region})
                elif isinstance(p, dict):
                    txt = _first(p, "query", "prompt", "text", "promptText", "name")
                    if txt:
                        prompts.append(txt)
                        queries.append({"text": txt,
                                        "topic": _first(p, "topic", "topicName", default="General"),
                                        "region": _first(p, "region", default=region)})
            if prompts:
                break

    # de-dup + cap
    seen, comp_clean = set(), []
    for c in competitors:
        c = (c or "").strip()
        if c and c.lower() not in seen:
            seen.add(c.lower())
            comp_clean.append(c)
    seenp, prompt_clean = set(), []
    for p in prompts:
        p = (p or "").strip()
        if p and p.lower() not in seenp:
            seenp.add(p.lower())
            prompt_clean.append(p)
    qmap = {}
    for q in queries:
        t = (q.get("text") or "").strip().lower()
        if t and t not in qmap:
            qmap[t] = q
    queries_clean = [qmap[p.lower()] for p in prompt_clean if p.lower() in qmap]

    definition = {
        "id": pid,
        "source": "workduo",
        "name": name,
        "brand": _first(entity, "name", default=name),
        "target": target,
        "domain": domain_of(target),
        "region": region,
        "entityId": str(eid) if eid else "",
        "alternativeNames": [a for a in alt if a][:10],
        "competitors": comp_clean[:8],
        "prompts": prompt_clean[:30],
        "queries": queries_clean[:30],
    }
    return definition, diag


# ---------------------------------------------------------------------------
# Handlers
# ---------------------------------------------------------------------------
def _now():
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def h_workduo_projects():
    projs = fetch_workduo_projects()
    light = [{
        "id": str(p.get("id")),
        "name": _first(p, "name", default=str(p.get("id"))),
        "domain": domain_of(_first(p.get("entity") or {}, "url", "domain", default="")),
        "hasEntity": bool((p.get("entity") or {}).get("id")),
    } for p in projs]
    return _resp(200, {"count": len(light), "projects": light})


def h_import(req):
    ids = [str(x) for x in (req.get("projectIds") or [])]
    dry = bool(req.get("dryRun"))
    projs = {str(p.get("id")): p for p in fetch_workduo_projects()}
    imported, diagnostics = [], {}
    targets = ids or list(projs.keys())[: int(req.get("limit", 5))]
    for pid in targets:
        project = projs.get(pid)
        if not project:
            diagnostics[pid] = "project_not_found"
            continue
        definition, diag = extract_definition(project)
        diagnostics[pid] = diag
        if not dry:
            item = dict(definition)
            item["createdAt"] = _now()
            item["updatedAt"] = _now()
            item["hasMetrics"] = False
            # don't clobber existing metrics on re-import
            existing = _table.get_item(Key={"id": pid}).get("Item")
            if existing and existing.get("metrics"):
                item["metrics"] = existing["metrics"]
                item["hasMetrics"] = True
                item["createdAt"] = existing.get("createdAt", item["createdAt"])
            _table.put_item(Item=item)
        imported.append(definition)
    return _resp(200, {"imported": len(imported), "dryRun": dry,
                       "campaigns": imported, "diagnostics": diagnostics})


def h_list():
    items, kwargs = [], {}
    while True:
        page = _table.scan(**kwargs)
        items.extend(page.get("Items", []))
        if "LastEvaluatedKey" not in page:
            break
        kwargs["ExclusiveStartKey"] = page["LastEvaluatedKey"]
    out = []
    for it in items:
        self_vis, days = None, 0
        if it.get("metrics"):
            try:
                mm = json.loads(it["metrics"])
                self_vis = (mm.get("self") or {}).get("visibility")
                days = len(mm.get("visibilitySeries") or [])
            except Exception:
                pass
        out.append({
            "id": it.get("id"), "name": it.get("name"), "brand": it.get("brand"),
            "target": it.get("target"), "domain": it.get("domain"), "region": it.get("region"),
            "competitors": it.get("competitors", []), "prompts": it.get("prompts", []),
            "alternativeNames": it.get("alternativeNames", []),
            "hasMetrics": bool(it.get("metrics")), "selfVisibility": self_vis, "dataDays": days,
            "metricsSource": it.get("metricsSource"),
            "updatedAt": it.get("updatedAt"), "metricsUpdatedAt": it.get("metricsUpdatedAt"),
        })
    out.sort(key=lambda c: (c.get("name") or "").lower())
    return _resp(200, {"count": len(out), "campaigns": out})


def h_get(req):
    cid = str(req.get("id") or "")
    it = _table.get_item(Key={"id": cid}).get("Item")
    if not it:
        return _resp(404, {"error": "not found"})
    if it.get("metrics"):
        try:
            it["metrics"] = json.loads(it["metrics"])
        except Exception:
            pass
    return _resp(200, {"campaign": it})


def h_save_metrics(req):
    cid = str(req.get("id") or "")
    model = req.get("model")
    if not cid or model is None:
        return _resp(400, {"error": "id and model required"})
    it = _table.get_item(Key={"id": cid}).get("Item")
    if not it:
        return _resp(404, {"error": "campaign not found — import it first"})
    _table.update_item(
        Key={"id": cid},
        UpdateExpression="SET #m = :m, hasMetrics = :h, metricsUpdatedAt = :t, updatedAt = :t",
        ExpressionAttributeNames={"#m": "metrics"},
        ExpressionAttributeValues={":m": json.dumps(model), ":h": True, ":t": _now()},
    )
    return _resp(200, {"ok": True, "id": cid, "metricsUpdatedAt": _now()})


def h_delete(req):
    cid = str(req.get("id") or "")
    _table.delete_item(Key={"id": cid})
    return _resp(200, {"ok": True, "deleted": cid})


PALETTE = ['#6b5ce7', '#14b8a6', '#f59e0b', '#ec4899', '#fda4af', '#38bdf8', '#a78bfa']
METRICS_DATE_RANGE = os.environ.get("WORKDUO_METRICS_RANGE", "last30days")


def _range_spec(req):
    """Resolve a date-range request into (query_string, preset, display_label).
    Workduo supports only last7days, last30days, or custom startDate/endDate."""
    dr = (req.get("dateRange") or "last30days").strip()
    if dr == "custom":
        sd, ed = req.get("startDate"), req.get("endDate")
        if not (sd and ed):
            raise RuntimeError("custom range requires startDate and endDate (YYYY-MM-DD)")
        return f"dateRange=custom&startDate={sd}&endDate={ed}", dr, f"{sd} → {ed}"
    if dr not in ("last7days", "last30days"):
        raise RuntimeError("unsupported dateRange — use last7days, last30days, or custom")
    return f"dateRange={dr}", dr, dr


def _wd_get_metrics(eid, pid, dimension, interval="daily", range_qs=None):
    """Paginated metrics rows for one entity/dimension over a window.
    interval='daily' for time-series, 'selectedDateRange' for one aggregate row each."""
    rows, token, pages, page_size = [], None, 0, 100
    rng = range_qs or f"dateRange={METRICS_DATE_RANGE}"
    base = (f"{WD_DATA}/metrics/entities/{eid}?projectId={pid}"
            f"&{rng}&dimension={dimension}&interval={interval}")
    while pages < 80:
        u = base + (f"&pageSize={page_size}" if page_size else "")
        if token:
            u += "&nextPageToken=" + token
        st, b = _wd_get(u)
        if st != 200:
            if page_size:          # some windows reject pageSize — retry without it
                page_size = 0
                continue
            break
        rows.extend(_rows(b))
        token = b.get("nextPageToken") if isinstance(b, dict) else None
        pages += 1
        if not token:
            break
    return rows


def _agg_overall(rows):
    m = sum(r.get("mentions", 0) or 0 for r in rows)
    resp = sum(r.get("totalResponses", 0) or 0 for r in rows)
    ent = sum(r.get("totalEntitiesMentions", 0) or 0 for r in rows)
    pos = [r["position"] for r in rows if r.get("position") and r.get("mentions")]
    occ = sum(r.get("ownedCitationCount", 0) or 0 for r in rows)
    ocs = [r.get("ownedCitationShare") for r in rows if r.get("ownedCitationShare") is not None]
    return {
        "visibility": round(m / resp * 100, 1) if resp else 0,
        "sov": round(m / ent * 100, 1) if ent else 0,
        "avgPosition": round(sum(pos) / len(pos), 1) if pos else 0,
        "mentions": m, "total": resp,
        "ownedCount": occ,
        "ownedShare": round(sum(ocs) / len(ocs) * 100, 1) if ocs else 0,
    }


def _daily(rows):
    by = {}
    for r in rows:
        d = (r.get("date") or "")[:10]
        if not d:
            continue
        x = by.setdefault(d, {"m": 0, "r": 0})
        x["m"] += r.get("mentions", 0) or 0
        x["r"] += r.get("totalResponses", 0) or 0
    return {d: round(x["m"] / x["r"] * 100, 1) if x["r"] else 0 for d, x in by.items()}


def _daily_by_topic(rows):
    """Per-topic daily visibility {date: {topic: vis%}} from topic-dimension daily rows.
    (Workduo returns one row per topic per day; _daily collapses that, this keeps it.)"""
    by = {}
    for r in rows:
        d = (r.get("date") or "")[:10]
        if not d:
            continue
        t = r.get("topic") or "General"
        x = by.setdefault(d, {}).setdefault(t, {"m": 0, "r": 0})
        x["m"] += r.get("mentions", 0) or 0
        x["r"] += r.get("totalResponses", 0) or 0
    return {d: {t: round(v["m"] / v["r"] * 100, 1) if v["r"] else 0 for t, v in tv.items()}
            for d, tv in by.items()}


def build_workduo_model(campaign, proj=None, range_qs=None, range_label=None):
    """Transform real Workduo metrics into the dashboard's WD.model shape.
    Sentiment + detailed citations are not exposed by Workduo's metrics API,
    so those are flagged unavailable rather than fabricated."""
    pid = str(campaign["id"])
    if proj is None:
        projects = {str(p.get("id")): p for p in fetch_workduo_projects()}
        proj = projects.get(pid) or {}
    self_eid = (proj.get("entity") or {}).get("id")
    brand = campaign.get("brand") or (proj.get("entity") or {}).get("name") or campaign.get("name")
    target = campaign.get("target") or (proj.get("entity") or {}).get("url") or ""
    domain = campaign.get("domain") or domain_of(target)
    region = campaign.get("region") or "Singapore"

    # entities (self + competitors)
    ents_raw = _rows(_wd_get(f"{WD_CORE}/entities", {"projectId": pid, "pageSize": 100})[1])
    metas = []
    for e in ents_raw:
        if not isinstance(e, dict) or not e.get("id"):
            continue
        metas.append({"id": e["id"], "name": e.get("name") or "",
                      "url": e.get("url") or "", "isSelf": e.get("id") == self_eid})
    # self first, then competitors; cap to keep within timeout
    metas.sort(key=lambda m: 0 if m["isSelf"] else 1)
    metas = metas[:6]

    # queryId -> text/topic
    qmap = {}
    for q in _rows(_wd_get(f"{WD_CORE}/queries", {"projectId": pid, "pageSize": 200})[1]):
        if isinstance(q, dict) and q.get("id"):
            qmap[q["id"]] = {"text": q.get("query") or q["id"],
                             "topic": q.get("topic") or "General",
                             "region": q.get("region") or region}

    ent_models, series_by_date = [], {}
    self_qrows, primary_qrows, primary_name = None, None, None
    self_topic_daily = {}
    for em in metas:
        trows = _wd_get_metrics(em["id"], pid, "topic", range_qs=range_qs)
        agg = _agg_overall(trows)
        nm = em["name"] or em["id"]
        ent_models.append({
            "name": nm, "domain": domain_of(em["url"]) or (domain if em["isSelf"] else ""),
            "isSelf": em["isSelf"], **agg,
        })
        for d, v in _daily(trows).items():
            series_by_date.setdefault(d, {})[nm] = v
        if em["isSelf"]:
            # keep the per-topic daily split for the tracked brand (powers the chart's topic filter)
            self_topic_daily = _daily_by_topic(trows)
            # one aggregate row per query (interval=selectedDateRange) — fast, no per-day pages
            self_qrows = _wd_get_metrics(em["id"], pid, "query", "selectedDateRange", range_qs=range_qs)
        elif primary_qrows is None:
            primary_qrows = _wd_get_metrics(em["id"], pid, "query", "selectedDateRange", range_qs=range_qs)
            primary_name = nm

    ent_models.sort(key=lambda e: -e["visibility"])
    self_m = next((e for e in ent_models if e["isSelf"]), ent_models[0] if ent_models else None)
    if not self_m:
        raise RuntimeError("no entity metrics returned from Workduo")

    # SOV breakdown (top 5 by sov + Others)
    by_sov = sorted(ent_models, key=lambda e: -e["sov"])
    sov_break, used = [], 0
    for i, e in enumerate(by_sov[:5]):
        sov_break.append({"name": e["name"], "value": e["sov"],
                          "color": PALETTE[i % len(PALETTE)], "isSelf": e["isSelf"]})
        used += e["sov"]
    rest = round(max(0, 100 - used), 1)
    if rest > 0.5:
        sov_break.append({"name": "Others", "value": rest, "color": "#cbd5e1", "isSelf": False})

    # visibility-over-time by brand (+ per-topic split for the tracked brand)
    vis_series = []
    for d in sorted(series_by_date.keys()):
        bb = series_by_date[d]
        vis_series.append({"date": d, "self": bb.get(self_m["name"], 0), "sov": self_m["sov"],
                           "positive": 0, "negative": 0, "byBrand": bb,
                           "byTopic": self_topic_daily.get(d, {})})

    # per-query breakdown (self vs primary competitor)
    comp_by_q = {}
    for r in (primary_qrows or []):
        qid = r.get("queryId")
        c = comp_by_q.setdefault(qid, {"m": 0, "r": 0})
        c["m"] += r.get("mentions", 0) or 0
        c["r"] += r.get("totalResponses", 0) or 0
    prompts = []
    byq = {}
    for r in (self_qrows or []):
        qid = r.get("queryId")
        x = byq.setdefault(qid, {"m": 0, "r": 0, "pos": []})
        x["m"] += r.get("mentions", 0) or 0
        x["r"] += r.get("totalResponses", 0) or 0
        if r.get("position") and r.get("mentions"):
            x["pos"].append(r["position"])
    for qid, x in byq.items():
        info = qmap.get(qid, {})
        selfpct = round(x["m"] / x["r"] * 100, 1) if x["r"] else 0
        c = comp_by_q.get(qid)
        comppct = round(c["m"] / c["r"] * 100, 1) if (c and c["r"]) else 0
        prompts.append({"text": info.get("text", qid), "topic": info.get("topic", "General"),
                        "region": info.get("region", region), "responses": x["r"],
                        "visibility": selfpct, "sov": self_m["sov"],
                        "avgPosition": round(sum(x["pos"]) / len(x["pos"]), 1) if x["pos"] else 0,
                        "selfPct": selfpct, "competitorPct": comppct})
    prompts.sort(key=lambda p: -p["visibility"])

    return {
        "brand": brand, "target": target, "domain": domain, "location": region,
        "live": True, "metricsSource": "workduo", "engineLabel": "Workduo (historical)",
        "generatedAt": _now(),
        "self": self_m, "entities": ent_models, "sovBreakdown": sov_break,
        "visibilitySeries": vis_series,
        "sentimentSeries": [{"date": s["date"], "positive": 0, "negative": 0} for s in vis_series],
        "prompts": prompts, "primaryComp": primary_name,
        "citations": [], "citationTypes": [],
        "ownedShare": self_m["ownedShare"], "ownedCount": self_m["ownedCount"],
        "positive": 0, "negative": 0, "sentimentThemes": [],
        "sentimentAvailable": False, "citationsDetailAvailable": False,
        "plats": [{"label": "ChatGPT"}, {"label": "Google AI Overview"}],
        "dateRange": range_label or METRICS_DATE_RANGE,
    }


# ---------------------------------------------------------------------------
# Daily export to geoCampaignDaily + Workduo-INDEPENDENT model builder.
# After export, the platform serves any date range straight from DynamoDB with
# zero Workduo calls — so Workduo access can be cut off entirely.
# ---------------------------------------------------------------------------
def _today():
    return datetime.now(timezone.utc).date()


def _blank():
    return {"m": 0, "r": 0, "em": 0, "ps": 0.0, "pc": 0, "oc": 0, "os": 0.0, "on": 0}


def _acc_overall(dst, r):
    dst["m"] += r.get("mentions", 0) or 0
    dst["r"] += r.get("totalResponses", 0) or 0
    dst["em"] += r.get("totalEntitiesMentions", 0) or 0
    if r.get("mentions") and r.get("position"):
        dst["ps"] += r["position"]; dst["pc"] += 1
    dst["oc"] += r.get("ownedCitationCount", 0) or 0
    if r.get("ownedCitationShare") is not None:
        dst["os"] += r["ownedCitationShare"]; dst["on"] += 1


def export_daily(campaign, proj=None, max_windows=3):
    """Pull available daily history from Workduo and store it per (campaign, date)
    in geoCampaignDaily. Walks backward in 30-day windows until the data runs out
    (capped at 3 windows ≈ 90 days — campaigns are recent)."""
    pid = str(campaign["id"])
    if proj is None:
        proj = {str(p.get("id")): p for p in fetch_workduo_projects()}.get(pid) or {}
    self_eid = (proj.get("entity") or {}).get("id")
    brand = campaign.get("brand") or (proj.get("entity") or {}).get("name") or campaign.get("name")
    target = campaign.get("target") or (proj.get("entity") or {}).get("url") or ""
    domain = campaign.get("domain") or domain_of(target)
    region = campaign.get("region") or "Singapore"

    ents_raw = _rows(_wd_get(f"{WD_CORE}/entities", {"projectId": pid, "pageSize": 100})[1])
    metas = []
    for e in ents_raw:
        if isinstance(e, dict) and e.get("id"):
            metas.append({"id": str(e["id"]), "name": e.get("name") or "",
                          "url": e.get("url") or "", "isSelf": e.get("id") == self_eid})
    metas.sort(key=lambda m: 0 if m["isSelf"] else 1)
    metas = metas[:6]
    primary_id = next((m["id"] for m in metas if not m["isSelf"]), None)

    qmeta = {}
    for q in _rows(_wd_get(f"{WD_CORE}/queries", {"projectId": pid, "pageSize": 200})[1]):
        if isinstance(q, dict) and q.get("id"):
            qmeta[str(q["id"])] = {"text": q.get("query") or str(q["id"]), "topic": q.get("topic") or "General"}

    days = {}

    def day(d):
        return days.setdefault(d, {"ents": {}})

    # Per-entity overall daily metrics only (topic-daily is cheap: few topics/day).
    # This is range-accurate for the time-series, KPIs, SOV and competitor leaderboard.
    # The per-query breakdown table is sourced from the persisted snapshot in build_model_from_db.
    today, empty, windows_used = _today(), 0, 0
    for w in range(max_windows):
        end = today - timedelta(days=w * 30)
        start = end - timedelta(days=29)
        qs = f"dateRange=custom&startDate={start.isoformat()}&endDate={end.isoformat()}"
        win_rows = 0
        for em in metas:
            for r in _wd_get_metrics(em["id"], pid, "topic", "daily", range_qs=qs):
                d = (r.get("date") or "")[:10]
                if not d:
                    continue
                win_rows += 1
                _acc_overall(day(d)["ents"].setdefault(em["id"], _blank()), r)
                if em["isSelf"]:
                    # keep the tracked brand's per-topic split so the range view can plot topic trends
                    t = r.get("topic") or "General"
                    st = day(d).setdefault("selfTopics", {}).setdefault(t, {"m": 0, "r": 0})
                    st["m"] += r.get("mentions", 0) or 0
                    st["r"] += r.get("totalResponses", 0) or 0
        windows_used = w + 1
        empty = empty + 1 if win_rows == 0 else 0
        if empty >= 2:
            break

    primary_name = next((m["name"] for m in metas if m["id"] == primary_id), None)
    meta = {"brand": brand, "target": target, "domain": domain, "region": region,
            "primaryId": primary_id, "primaryName": primary_name,
            "entities": {m["id"]: {"name": m["name"], "url": m["url"], "isSelf": m["isSelf"]} for m in metas}}
    _daily_tbl.put_item(Item={"campaignId": pid, "date": "__meta__", "blob": json.dumps(meta)})
    with _daily_tbl.batch_writer() as bw:
        for d, data in days.items():
            bw.put_item(Item={"campaignId": pid, "date": d, "blob": json.dumps(data)})
    # mark the definition row so the frontend knows daily data is queryable
    try:
        _table.update_item(Key={"id": pid},
                           UpdateExpression="SET hasDaily = :h, dailyDays = :d, dailyUpdatedAt = :t",
                           ExpressionAttributeValues={":h": True, ":d": len(days), ":t": _now()})
    except Exception:
        pass
    return {"days": len(days), "windows": windows_used, "entities": len(metas)}


def _range_dates(req):
    dr = (req.get("dateRange") or "last30days").strip()
    today = _today()
    if dr == "custom":
        sd, ed = req.get("startDate"), req.get("endDate")
        if not (sd and ed):
            raise RuntimeError("custom range requires startDate and endDate (YYYY-MM-DD)")
        return sd, ed, dr, f"{sd} → {ed}"
    if dr == "last7days":
        return (today - timedelta(days=6)).isoformat(), today.isoformat(), dr, dr
    if dr == "last30days":
        return (today - timedelta(days=29)).isoformat(), today.isoformat(), dr, dr
    raise RuntimeError("unsupported dateRange — use last7days, last30days, or custom")


def build_model_from_db(cid, start, end, label):
    """Build the dashboard model for a date range entirely from geoCampaignDaily — no Workduo."""
    meta_item = _daily_tbl.get_item(Key={"campaignId": cid, "date": "__meta__"}).get("Item")
    if not meta_item:
        raise RuntimeError("no daily data exported for this campaign yet")
    meta = json.loads(meta_item["blob"])
    ents_meta, primary_id = meta["entities"], meta.get("primaryId")

    cond = Key("campaignId").eq(cid) & Key("date").between(start, end)
    resp = _daily_tbl.query(KeyConditionExpression=cond)
    items = resp.get("Items", [])
    while "LastEvaluatedKey" in resp:
        resp = _daily_tbl.query(KeyConditionExpression=cond, ExclusiveStartKey=resp["LastEvaluatedKey"])
        items.extend(resp.get("Items", []))

    ent_tot, series, topic_by_date = {}, {}, {}
    for it in items:
        d = it["date"]
        data = json.loads(it["blob"])
        for eid, ov in data.get("ents", {}).items():
            t = ent_tot.setdefault(eid, _blank())
            for k in t:
                t[k] += ov.get(k, 0)
            nm = (ents_meta.get(eid) or {}).get("name") or eid
            series.setdefault(d, {})[nm] = round(ov["m"] / ov["r"] * 100, 1) if ov.get("r") else 0
        st = data.get("selfTopics") or {}
        if st:
            topic_by_date[d] = {tp: round(v["m"] / v["r"] * 100, 1) if v.get("r") else 0
                                for tp, v in st.items()}

    def overall(t):
        return {"visibility": round(t["m"] / t["r"] * 100, 1) if t["r"] else 0,
                "sov": round(t["m"] / t["em"] * 100, 1) if t["em"] else 0,
                "avgPosition": round(t["ps"] / t["pc"], 1) if t["pc"] else 0,
                "mentions": t["m"], "total": t["r"], "ownedCount": t["oc"],
                "ownedShare": round(t["os"] / t["on"] * 100, 1) if t["on"] else 0}

    ent_models = []
    for eid, t in ent_tot.items():
        em = ents_meta.get(eid) or {}
        ent_models.append({"name": em.get("name") or eid,
                           "domain": domain_of(em.get("url")) or (meta["domain"] if em.get("isSelf") else ""),
                           "isSelf": bool(em.get("isSelf")), **overall(t)})
    ent_models.sort(key=lambda e: -e["visibility"])
    self_m = next((e for e in ent_models if e["isSelf"]), ent_models[0] if ent_models else None)
    if not self_m:
        raise RuntimeError("no entity data in selected range")

    by_sov = sorted(ent_models, key=lambda e: -e["sov"])
    sov_break, used = [], 0
    for i, e in enumerate(by_sov[:5]):
        sov_break.append({"name": e["name"], "value": e["sov"], "color": PALETTE[i % len(PALETTE)], "isSelf": e["isSelf"]})
        used += e["sov"]
    rest = round(max(0, 100 - used), 1)
    if rest > 0.5:
        sov_break.append({"name": "Others", "value": rest, "color": "#cbd5e1", "isSelf": False})

    vis_series = []
    for d in sorted(series.keys()):
        bb = series[d]
        vis_series.append({"date": d, "self": bb.get(self_m["name"], 0), "sov": self_m["sov"],
                           "positive": 0, "negative": 0, "byBrand": bb,
                           "byTopic": topic_by_date.get(d, {})})

    # Per-query breakdown: reuse the persisted last-30d snapshot. (Workduo doesn't expose
    # per-query daily cheaply; the time-series / KPIs / SOV / competitors above ARE range-accurate.)
    prompts = []
    snap = _table.get_item(Key={"id": cid}).get("Item")
    if snap and snap.get("metrics"):
        try:
            prompts = (json.loads(snap["metrics"]) or {}).get("prompts", []) or []
        except Exception:
            prompts = []
    primary_name = meta.get("primaryName") or ((ents_meta.get(primary_id) or {}).get("name") if primary_id else None)

    return {"brand": meta["brand"], "target": meta["target"], "domain": meta["domain"], "location": meta["region"],
            "live": True, "metricsSource": "workduo", "engineLabel": "Workduo (historical)", "generatedAt": _now(),
            "self": self_m, "entities": ent_models, "sovBreakdown": sov_break, "visibilitySeries": vis_series,
            "sentimentSeries": [{"date": s["date"], "positive": 0, "negative": 0} for s in vis_series],
            "prompts": prompts, "primaryComp": primary_name, "citations": [], "citationTypes": [],
            "ownedShare": self_m["ownedShare"], "ownedCount": self_m["ownedCount"],
            "positive": 0, "negative": 0, "sentimentThemes": [], "sentimentAvailable": False,
            "citationsDetailAvailable": False, "plats": [{"label": "ChatGPT"}, {"label": "Google AI Overview"}],
            "dateRange": label, "dataSource": "db"}


def h_export_daily(req):
    cid = str(req.get("id") or "")
    item = _table.get_item(Key={"id": cid}).get("Item")
    proj = {str(p.get("id")): p for p in fetch_workduo_projects()}.get(cid)
    r = export_daily(item or {"id": cid}, proj=proj)
    return _resp(200, {"id": cid, **r})


def h_export_daily_all(req):
    flt = (req.get("filter") or "(Live)").lower()
    force = bool(req.get("force"))
    projs = fetch_workduo_projects()
    matched = [p for p in projs if flt in (p.get("name") or "").lower() and (p.get("entity") or {}).get("id")]
    results = []
    for p in matched:
        pid, name = str(p.get("id")), (p.get("name") or "")
        if not force and _daily_tbl.get_item(Key={"campaignId": pid, "date": "__meta__"}).get("Item"):
            results.append({"id": pid, "name": name, "status": "skipped"})
            continue
        item = _table.get_item(Key={"id": pid}).get("Item") or {"id": pid, "brand": name}
        try:
            r = export_daily(item, proj=p)
            results.append({"id": pid, "name": name, "status": "done", **r})
        except Exception as e:
            results.append({"id": pid, "name": name, "status": "error", "error": str(e)})
    return _resp(200, {"matched": len(matched),
                       "done": len([r for r in results if r["status"] == "done"]),
                       "skipped": len([r for r in results if r["status"] == "skipped"]),
                       "errors": [r for r in results if r["status"] == "error"], "results": results})


def h_import_metrics(req):
    cid = str(req.get("id") or "")
    it = _table.get_item(Key={"id": cid}).get("Item")
    if not it:
        return _resp(404, {"error": "campaign not found — import its definition first"})
    model = build_workduo_model(it)
    _table.update_item(
        Key={"id": cid},
        UpdateExpression="SET #m = :m, hasMetrics = :h, metricsUpdatedAt = :t, updatedAt = :t, metricsSource = :s",
        ExpressionAttributeNames={"#m": "metrics"},
        ExpressionAttributeValues={":m": json.dumps(model), ":h": True, ":t": _now(), ":s": "workduo"},
    )
    return _resp(200, {"ok": True, "id": cid, "entities": len(model["entities"]),
                       "prompts": len(model["prompts"]), "days": len(model["visibilitySeries"]),
                       "self": model["self"]})


def h_metrics_for_range(req):
    """On-demand: build a campaign's model for a chosen date range straight from our
    DynamoDB daily store — NO Workduo calls. Fast (single DynamoDB date-range query)."""
    cid = str(req.get("id") or "")
    start, end, preset, label = _range_dates(req)
    model = build_model_from_db(cid, start, end, label)
    model["dateRangePreset"] = preset
    return _resp(200, {"id": cid, "model": model})


def h_migrate_all(req):
    """Resumable batch migration of Workduo projects matching `filter` (default '(Live)').
    Imports definition + real historical metrics for each, skipping any that already have
    metrics (unless force=true) and continuing past per-campaign errors. Idempotent — safe
    to re-trigger; it resumes where it left off."""
    flt = (req.get("filter") or "(Live)").lower()
    with_metrics = req.get("withMetrics", True)
    force = bool(req.get("force"))
    projs = fetch_workduo_projects()
    matched = [p for p in projs
               if flt in (p.get("name") or "").lower() and (p.get("entity") or {}).get("id")]
    results = []
    for p in matched:
        pid = str(p.get("id"))
        name = p.get("name") or pid
        existing = _table.get_item(Key={"id": pid}).get("Item")
        if existing and existing.get("metrics") and not force:
            results.append({"id": pid, "name": name, "status": "skipped"})
            continue
        try:
            definition, _ = extract_definition(p)
            item = dict(definition)
            item["createdAt"] = (existing or {}).get("createdAt") or _now()
            item["updatedAt"] = _now()
            item["hasMetrics"] = False
            _table.put_item(Item=item)
            vis = None
            if with_metrics:
                model = build_workduo_model(item, proj=p)
                vis = (model.get("self") or {}).get("visibility")
                _table.update_item(
                    Key={"id": pid},
                    UpdateExpression="SET #m = :m, hasMetrics = :h, metricsUpdatedAt = :t, updatedAt = :t, metricsSource = :s",
                    ExpressionAttributeNames={"#m": "metrics"},
                    ExpressionAttributeValues={":m": json.dumps(model), ":h": True, ":t": _now(), ":s": "workduo"},
                )
            results.append({"id": pid, "name": name, "status": "done", "visibility": vis})
        except Exception as e:
            results.append({"id": pid, "name": name, "status": "error", "error": str(e)})
    return _resp(200, {
        "filter": req.get("filter") or "(Live)",
        "matched": len(matched),
        "done": len([r for r in results if r["status"] == "done"]),
        "skipped": len([r for r in results if r["status"] == "skipped"]),
        "errors": [r for r in results if r["status"] == "error"],
        "results": results,
    })


def h_inspect(req):
    """One-off discovery: dump a raw project + probe candidate prompt/region endpoints."""
    pid = str(req.get("id") or "")
    projs = {str(p.get("id")): p for p in fetch_workduo_projects()}
    p = projs.get(pid)
    eid = (p.get("entity") or {}).get("id") if p else None
    cand = [
        f"{WD_CORE}/projects/{pid}",
        f"{WD_CORE}/queries?projectId={pid}&pageSize=200",
        f"{WD_CORE}/prompts?projectId={pid}&pageSize=200",
        f"{WD_DATA}/metrics/entities/{eid}?projectId={pid}&dimension=query&dateRange=last30days",
        f"{WD_DATA}/metrics/entities/{eid}?projectId={pid}&dimension=prompt&dateRange=last30days",
        f"{WD_DATA}/queries?projectId={pid}&pageSize=200",
        f"{WD_CORE}/projects/{pid}/topics",
    ]
    probes = {}
    for u in cand:
        st, b = _wd_get(u)
        probes[u.replace(pid, "{id}").replace(str(eid), "{eid}")] = {"status": st, "sample": json.dumps(b)[:600]}
    return _resp(200, {"projectKeys": list(p.keys()) if p else None,
                       "project": p, "entityKeys": list((p.get("entity") or {}).keys()) if p else None,
                       "probes": probes})


def h_inspect_ranges(req):
    """Discover which dateRange presets + custom from/to params Workduo accepts."""
    pid = str(req.get("id") or "")
    projs = {str(p.get("id")): p for p in fetch_workduo_projects()}
    p = projs.get(pid)
    eid = (p.get("entity") or {}).get("id") if p else None
    base = f"{WD_DATA}/metrics/entities/{eid}?projectId={pid}&dimension=topic&interval=daily&pageSize=100"
    presets = ["last7days", "last14days", "last30days", "last90days", "last180days",
               "lastMonth", "thisMonth", "last3months", "last6months", "lastYear", "allTime"]
    custom = [
        "&dateRange=custom&dateFrom=2026-05-01&dateTo=2026-05-31",
        "&dateRange=custom&startDate=2026-05-01&endDate=2026-05-31",
        "&dateRange=custom&from=2026-05-01&to=2026-05-31",
        "&dateFrom=2026-05-01&dateTo=2026-05-31",
        "&startDate=2026-05-01&endDate=2026-05-31",
        "&dateRange=selectedDateRange&dateFrom=2026-05-01&dateTo=2026-05-31",
    ]
    probes = {}
    for r in presets:
        st, b = _wd_get(base + f"&dateRange={r}")
        rows = _rows(b) if st == 200 else []
        probes["preset:" + r] = {"status": st, "rows": len(rows), "msg": (b.get("message") or b.get("error") if isinstance(b, dict) else "")}
    for c in custom:
        st, b = _wd_get(base + c)
        rows = _rows(b) if st == 200 else []
        probes["custom:" + c] = {"status": st, "rows": len(rows), "msg": (b.get("message") or b.get("error") if isinstance(b, dict) else "")}
    return _resp(200, {"probes": probes})


def h_inspect_metrics(req):
    """Map the Workduo METRICS surface: probe dimensions/intervals + data endpoints."""
    pid = str(req.get("id") or "")
    projs = {str(p.get("id")): p for p in fetch_workduo_projects()}
    p = projs.get(pid)
    eid = (p.get("entity") or {}).get("id") if p else None
    base = f"{WD_DATA}/metrics/entities/{eid}?projectId={pid}&dateRange=last30days"
    cand = [
        base + "&dimension=date&interval=daily",
        base + "&dimension=query&interval=daily",
        base + "&dimension=topic",
        base + "&dimension=sentiment",
        base + "&dimension=citation",
        base + "&dimension=citationType",
        base + "&dimension=platform",
        base + "&dimension=competitor",
        base + "&dimension=entity",
        f"{WD_DATA}/metrics/projects/{pid}?dateRange=last30days",
        f"{WD_DATA}/metrics/projects/{pid}?dateRange=last30days&dimension=entity",
        f"{WD_DATA}/citations?projectId={pid}&dateRange=last30days&pageSize=50",
        f"{WD_DATA}/sentiment?projectId={pid}&dateRange=last30days",
        f"{WD_DATA}/sentiments?projectId={pid}&dateRange=last30days",
        f"{WD_DATA}/competitors?projectId={pid}&dateRange=last30days",
        f"{WD_CORE}/projects/{pid}/entities",
    ]
    probes = {}
    for u in cand:
        st, b = _wd_get(u)
        rows = _rows(b) if st == 200 else []
        probes[u.replace(str(pid), "{id}").replace(str(eid), "{eid}")] = {
            "status": st, "rowCount": len(rows),
            "rowKeys": (list(rows[0].keys()) if rows and isinstance(rows[0], dict) else None),
            "sample": json.dumps(b)[:500],
        }
    return _resp(200, {"entityId": eid, "probes": probes})


def lambda_handler(event, context):
    method = (event.get("requestContext", {}).get("http", {}).get("method")
              or event.get("httpMethod") or "POST")
    if method == "OPTIONS":
        return _resp(200, {"ok": True})

    raw = event.get("body")
    if raw is None and ("action" in event or "id" in event):
        req = event  # direct invoke convenience
    else:
        if event.get("isBase64Encoded") and isinstance(raw, str):
            raw = base64.b64decode(raw).decode()
        try:
            req = json.loads(raw) if isinstance(raw, str) else (raw or {})
        except Exception:
            req = {}

    action = req.get("action", "list")
    try:
        if action == "workduo_projects":
            return h_workduo_projects()
        if action == "import":
            return h_import(req)
        if action == "list":
            return h_list()
        if action == "get":
            return h_get(req)
        if action == "save_metrics":
            return h_save_metrics(req)
        if action == "delete":
            return h_delete(req)
        if action == "inspect":
            return h_inspect(req)
        if action == "inspect_metrics":
            return h_inspect_metrics(req)
        if action == "inspect_ranges":
            return h_inspect_ranges(req)
        if action == "import_metrics":
            return h_import_metrics(req)
        if action == "migrate_all":
            return h_migrate_all(req)
        if action == "metrics_for_range":
            return h_metrics_for_range(req)
        if action == "export_daily":
            return h_export_daily(req)
        if action == "export_daily_all":
            return h_export_daily_all(req)
        return _resp(400, {"error": f"unknown action: {action}"})
    except Exception as e:
        return _resp(500, {"error": str(e)})
